/*

 ALIEN_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define alien_tilesBank 0

/* Super Gameboy palette 0 */
#define alien_tilesSGBPal0c0 6076
#define alien_tilesSGBPal0c1 8935
#define alien_tilesSGBPal0c2 6596
#define alien_tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define alien_tilesSGBPal1c0 6076
#define alien_tilesSGBPal1c1 8935
#define alien_tilesSGBPal1c2 6596
#define alien_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define alien_tilesSGBPal2c0 6076
#define alien_tilesSGBPal2c1 8935
#define alien_tilesSGBPal2c2 6596
#define alien_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define alien_tilesSGBPal3c0 6076
#define alien_tilesSGBPal3c1 8935
#define alien_tilesSGBPal3c2 6596
#define alien_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define alien_tilesCGBPal0c0 6076
#define alien_tilesCGBPal0c1 8935
#define alien_tilesCGBPal0c2 6596
#define alien_tilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define alien_tilesCGBPal1c0 6076
#define alien_tilesCGBPal1c1 8935
#define alien_tilesCGBPal1c2 6596
#define alien_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define alien_tilesCGBPal2c0 6076
#define alien_tilesCGBPal2c1 8935
#define alien_tilesCGBPal2c2 6596
#define alien_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define alien_tilesCGBPal3c0 6076
#define alien_tilesCGBPal3c1 8935
#define alien_tilesCGBPal3c2 6596
#define alien_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define alien_tilesCGBPal4c0 6076
#define alien_tilesCGBPal4c1 8935
#define alien_tilesCGBPal4c2 6596
#define alien_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define alien_tilesCGBPal5c0 6076
#define alien_tilesCGBPal5c1 8935
#define alien_tilesCGBPal5c2 6596
#define alien_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define alien_tilesCGBPal6c0 6076
#define alien_tilesCGBPal6c1 8935
#define alien_tilesCGBPal6c2 6596
#define alien_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define alien_tilesCGBPal7c0 6076
#define alien_tilesCGBPal7c1 8935
#define alien_tilesCGBPal7c2 6596
#define alien_tilesCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char alien_tiles[];

/* End of ALIEN_TILES.H */
