//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bigShip_H
#define METASPRITE_bigShip_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bigShip_TILE_ORIGIN 0
#define bigShip_TILE_W 8
#define bigShip_TILE_H 8
#define bigShip_WIDTH 64
#define bigShip_HEIGHT 96
#define bigShip_TILE_COUNT 96
#define bigShip_PALETTE_COUNT 1
#define bigShip_COLORS_PER_PALETTE 4
#define bigShip_TOTAL_COLORS 4
#define bigShip_MAP_ATTRIBUTES 0

BANKREF_EXTERN(bigShip)

extern const palette_color_t bigShip_palettes[4];
extern const uint8_t bigShip_tiles[1536];

extern const unsigned char bigShip_map[96];

#endif
