//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_boss_H
#define METASPRITE_boss_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define boss_TILE_ORIGIN 0
#define boss_TILE_W 8
#define boss_TILE_H 8
#define boss_WIDTH 64
#define boss_HEIGHT 96
#define boss_TILE_COUNT 96
#define boss_PALETTE_COUNT 1
#define boss_COLORS_PER_PALETTE 4
#define boss_TOTAL_COLORS 4
#define boss_MAP_ATTRIBUTES 0

BANKREF_EXTERN(boss)

extern const palette_color_t boss_palettes[4];
extern const uint8_t boss_tiles[1536];

extern const unsigned char boss_map[96];

#endif
