/*

 SCENE1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 32
   Tile set      : scene_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Scene1Width 128
#define Scene1Height 32
#define Scene1Bank 0

extern unsigned char Scene1[];

/* End of SCENE1.H */
