/*

 SCENE1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Scene1Width 64
#define Scene1Height 64
#define Scene1Bank 0

extern unsigned char Scene1[];

/* End of SCENE1.H */
